### PR TITLE
Update release-process.rst to fix two typos

### PR DESCRIPTION
**Pull request by DanielEScherzer**

### CODE REVIEW

**Comment by cmb69** [comment]
Huh! Not sure why CI complains.

**Comment by DanielEScherzer** [comment]
I think its because of #8 not being done yet, since the failures are from multiple files:
```
coding-standards-and-naming.rst is not correctly formatted!
feature-proposals.rst is not correctly formatted!
release-process.rst is not correctly formatted!
security-classification.rst is not correctly formatted!
security-policies.rst is not correctly formatted!
```

**Comment by derickr** [comment]
That's odd. They were working earlier.

I'll have a look tomorrow.

**Comment by cmb69** [comment]
@derickr, #8 has not been merged, but the CI check is already in place.

**Comment by DanielEScherzer** [comment]
> That's odd. They were working earlier. I'll have a look tomorrow.

@derickr any updates?

**Comment by derickr** [comment]
Sorry, not yet. Many things going on right now.

**Comment by derickr** [comment]
Ah right, could you rebase this? It should work then.

**Comment by DanielEScherzer** [comment]
> Ah right, could you rebase this? It should work then. (it conflicts now)

Done

**Comment by cmb69** [comment]
Thank you!

**Pull request merged**
