### PR TITLE
Include the acronym casing RFC in coding-standards-and-naming.rst

### PR DESCRIPTION
**Pull request by TimWolla**
see https://wiki.php.net/rfc/class-naming-acronyms

---------

Companion RFC in php/php-src#14169.

/cc @crell @nielsdos @girgias

### CODE REVIEW

**Review by nielsdos — APPROVED** [review]
I don't know if the policy should be an evolving document, Derick will know that.
But the contents itself look good.

**Review by derickr — CHANGES_REQUESTED** [review]
The idea behind these documents is that they **update** the actual text — not adding a new section that has changes to already existing text.

At the top, you can do something like:

https://github.com/php/policies/blob/main/release-process.rst?plain=1#L8

**Comment by TimWolla** [comment]
> The idea behind these documents is that they **update** the actual text — not adding a new section that has changes to already existing text.

My understanding is that the coding-standards-and-naming.rst has not yet been cleaned up following the “Policy Repository” RFC:

> Once (and if) this RFC is accepted, a first new step would be to rephrase the text so that it reads like a policy document, instead of an RFC. The wording is currently exactly as in the used RFCs, without modification.

… and thus still is the concatenation of the relevant RFCs instead of a properly written policy document.

I feel that editing around in the existing non-cleaned-up state would make things worse rather than better, because the result is neither a coherent text, nor does it match the RFC texts that are authoritative as-of now.

**Comment by TimWolla** [comment]
In fact as per my understanding of the “Policy Repository” RFC, the cleaning up requires another RFC to confirm that no unintended changes have been introduced:

> Both of these will be implemented through a separate PR to the policy repository. After comment integration, an RFC will be created to confirm these changes.

The previous PR for the release cycle update is already merged and thus to my understanding violates that decision.

**Comment by derickr** [comment]
Hmm, you're right. I had missed that from my own RFC :-). The question is... does it actually make sense to do?

But I would also say, that it probably have been wise to cover that in your "acronym casing policy" RFC so that we don't need to do it twice!

**Comment by derickr** [comment]
OK, please merge this then. I will then start working on fixing up all the language and put it up for an RFC.

**Comment by TimWolla** [comment]
Sorry, didn't get around to this over the weekend and was busy last week.

> But I would also say, that it probably have been wise to cover that in your "acronym casing policy" RFC so that we don't need to do it twice!

I've written the RFC in a way such that it makes a well-defined change to the CODING_STANDARDS.md. That one is the more complete file, compared to the stuff in the policies repository and thus is probably the best source for the rewrite.

> OK, please merge this then.

I don't have the commit bit for this repository, someone else will need to merge.

> I will then start working on fixing up all the language and put it up for an RFC.

Thank you.

**Pull request merged**
